//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbfirst_15323
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent
    {
        public int stnd_id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> rollno { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> state { get; set; }
    }
}
